print("hello")
print("world")
print("Not so good")
print("goodbye")
print("goodbye again")
print("This is a test")
print("This is another test")
print("This is a final test")
print("This is a final test again")
print("This is a final test once more")
print("This is a final test yet again")

